Model.Connections
Model.GetChildren(DataModelObjectCategory.Connections,True)
conn=Model.Connections
conn.Activate()
conngrp=conn.AddConnectionGroup()
conngrp.ConnectionType
conngrp.ConnectionType=AutoDetectionType.Joint
conngrp.ConnectionType=AutoDetectionType.Contact
congrp.Location
conngrp.Location
conngrp.Location
conngrp.Location
conngrp.ToleranceType
conngrp.ToleranceType=ContactToleranceType.Value
conngrp.ToleranceValue
conngrp.ToleranceValue=Quantity(0.1,'mm')
conngrp.CreateAutomaticConnections()
conngrp.FaceEdge
conngrp.FaceEdge=ContactFaceEdgeOption.Yes
conngrp.CreateAutomaticConnections()
conngrp.Connections
conngrp2=conn.AddConnectionGroup()
conngrp2.ConnectionType=AutoDetectionType.Joint
conngrp2.ToleranceType=ContactToleranceType.Slider
conngrp2.ToleranceType=ContactToleranceType.Value
conngrp.ToleranceValue=Quantity(0.1,'mm')
conngrp2.CreateAutomaticConnections()
conn.GenerateAutomaticConnectionOnRefresh=AutomaticOrManual.Manual
