ExtAPI.DataModel.Project.Model.Analyses
ExtAPI.DataModel.Project.Model.Analyses[0].GeoData
ExtAPI.DataModel.GeoData
ExtAPI.DataModel.AnalysisList
ExtAPI.DataModel.AnalysisList[0].GeoData
gd=ExtAPI.DataModel.GeoData
gd.GetType
gd.GetType()
gd.Assemblies
gd.ToString
gd.ToString()
gd.ToString()='Ansys.ACT.Common.Geometry.GeometryWrapper'
gd.ToString='Ansys.ACT.Common.Geometry.GeometryWrapper'
gd.ToString()=='Ansys.ACT.Common.Geometry.GeometryWrapper'
gd.Assemblies[0]
assy=gd.Assemblies[0]
assy.AllParts
assy.Parts
assy.Unit
assy.Parts[0]
p1=assy.Parts[0]
p1.Bodies
p2=assy.AllParts[1]
p2.Bodies
p1
b1=p1.Bodies
b1
b1.Area
b1.Area
b1.Area
b1.BodyType
b1=p1.Bodies[0]
b1
b1.Area
b1.BodyType
b1.Centroid
b1.Faces
len(b1.Faces)
b1.Vertices
len(b1.Vertices)
b1.Edges
len(b1.Edges)
b1.GeoData
b1.Id
selinfo=ExtAPI.SelectionManager.CreateSelectionInfo(SelectionTypeEnumGeometry)
selinfo=ExtAPI.SelectionManager.CreateSelectionInfo(SelectionTypeEnum.Geometry)
selinfo=ExtAPI.SelectionManager.CreateSelectionInfo(SelectionTypeEnum.GeometryEntities)
selinfo.Ids
selinfo.Ids=[b1.Id]
ExtAPI.SelectionManager.NewSelection(selinfo)
ExtAPI.SelectionManager.NewSelection(selinfo)
b1.Material
b1.Faces
len(b1.Faces)
f1=b1.Faces[0]
f1
f1.Id
selinfo.Ids=[14]
ExtAPI.SelectionManager.NewSelection(selinfo)
f1.Area
f1.Centroid
f1.Centroid[0]
f1.Centroid[1]
f1.Centroid[2]
f1.SurfaceeType
f1.SurfaceType
f1.GetBoundingBox
f1.GetBoundingBox()
f1.Points
f1.Parts
f1.Part
f1.Bodies
f1.Edges
len(f1.Edges)
e1=f1.Edges[0]
e1
e1.Id
selinfo.Ids=[20]
ExtAPI.SelectionManager.newSelection(selinfo)
ExtAPI.SelectionManager.NewSelection(selinfo)
e1.Centroid
e1.CurveType
e1.GetBoundingBox
e1.GetBoundingBox()
e1.Vertices
V1.Id
v1.Ids
v1=e1.Vertices[0]
v1.ids
v1.Id
selinfo.Ids=[37]
ExtAPI.SelectionManager.NewSelection(selinfo)
v1.X
v1.Y
gd
gd.GeoEntityById(14)
ExtAPI.DataModel.Project.Model.Geometry
Model
Model.Geometry
Model.Geometry.Bodies
Model.Geometry.GetBody(b1)
Model.Geometry.SolidBodies
Model.Geometry.Children
Model.Geometry.Children[1]
Model.Geometry.Children[1].Children[0]
b11=Model.Geometry.Children[1].Children[0]
b11.GetGeoBody()
